services:
    api:
        image: trungisdead1/php:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_ENV=${APP_ENV}
        container_name: api
        environment:
            - APP_ENV=${APP_ENV}
        env_file:
            - .env
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - db-mysql

    db-mysql:
        container_name: db-mysql
        image: mysql:8.0
        ports:
            -   3307:3307
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data: ~
